filebeat.inputs:
- type: container
  paths:
    - /var/lib/docker/containers/*/*.log

processors:
- add_docker_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]

# Añadir logging de debug
logging.level: debug
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644